graphql:
  servlet:
    mapping: /graphql

graphiql:
    mapping: /
    endpoint:
      graphql: /graphql
      subscriptions: /subscriptions
    subscriptions:
      timeout: 30
      reconnect: false
    enabled: true
    pageTitle: GraphiQL
    
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
        loggerLevel: basic

tmdb:
  apiKey: 7bcb7cf225f10be665a9337df22a8488
  apiURL: http://api.themoviedb.org/3
  image:
    baseURL: http://image.tmdb.org/t/p/
    size:
      backdrop: w300, w780, w1280, original
      poster: w92, w185, w342, original
      logo: w45, w154, w300, original
      profile: w45, w185, h632, original

logging:
  level:
    root: INFO
    graphql.servlet.internal: ERROR
    com.example: DEBUG